import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { useRouter } from 'next/router'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

type Locale = 'en' | 'sv' | 'es' | 'de';

type Translation = {
  [key in Locale]: {
    text: string
  }
}

const languages: Translation = {
  en: {
    text: "Get started by editing"
  },
  sv: {
    text: "Börja med att redigera"
  },
  es: {
    text: "Comience editando"
  },
  de: {
    text: "Beginnen Sie mit dem Bearbeiten"
  }
} as const

export default function Home() {
  const {locale} = useRouter()

  const currentLocale = locale ?? 'sv'
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <p>
            {languages[currentLocale as keyof typeof languages].text}&nbsp;
            <code className={styles.code}>pages/index.tsx</code>
          </p>
          <div>
            <a
              href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              target="_blank"
              rel="noopener noreferrer"
            >
              By{' '}
              <Image
                src="/vercel.svg"
                alt="Vercel Logo"
                className={styles.vercelLogo}
                width={100}
                height={24}
                priority
              />
            </a>
          </div>
        </div>

        <div className={styles.center}>
          <Image
            className={styles.logo}
            src="/next.svg"
            alt="Next.js Logo"
            width={180}
            height={37}
            priority
          />
          <div className={styles.thirteen}>
            <Image
              src="/thirteen.svg"
              alt="13"
              width={40}
              height={31}
              priority
            />
          </div>
        </div>

        <div className={styles.grid}>
            <Link href="/" locale="en" className={styles.card}>
            <h2 className={inter.className}>
              English <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Change the language to English here.
            </p>
          </Link>

          <Link href="/" locale="sv" className={styles.card}>
            <h2 className={inter.className}>
              Swedish <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Ändra språket till svenska här.
            </p>
          </Link>

          <Link href="/" locale="es" className={styles.card}>
            <h2 className={inter.className}>
              Spanish <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Cambia el idioma al español aquí.
            </p>
          </Link>

          <Link href="/" locale="de" className={styles.card}>
            <h2 className={inter.className}>
              German <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Ändern Sie die Sprache auf Deutsch hier.
            </p>
          </Link>
        </div>
      </main>
    </>
  )
}
